# **IMPORT LIBRARIES**

---

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# **IMPORT DATA**

---

In [2]:
# import "weight-height.csv"
from google.colab import files
files.upload()

Saving weight-height.csv to weight-height.csv

{'weight-height.csv': b'Gender,Height,Weight\r\nMale,73.847017017515,241.893563180437\r\nMale,68.7819040458903,162.310472521300\r\nMale,74.1101053917849,212.7408555565\r\nMale,71.7309784033377,220.042470303077\r\nMale,69.8817958611153,206.349800623871\r\nMale,67.2530156878065,152.212155757083\r\nMale,68.7850812516616,183.927888604031\r\nMale,68.3485155115879,167.971110489509\r\nMale,67.018949662883,175.92944039571\r\nMale,63.4564939783664,156.399676387112\r\nMale,71.1953822829745,186.604925560358\r\nMale,71.6408051192206,213.741169489411\r\nMale,64.7663291334055,167.127461073476\r\nMale,69.2830700967204,189.446181386738\r\nMale,69.2437322298112,186.434168021239\r\nMale,67.6456197004212,172.186930058117\r\nMale,72.4183166259878,196.028506330482\r\nMale,63.974325721061,172.883470208780\r\nMale,69.6400598997523,185.983957573130\r\nMale,67.9360048540095,182.426648013226\r\nMale,67.9150501938206,174.115929081393\r\nMale,69.4394398680395,197.73142161472\r\nMale,66.1491319608781,149.173566007975\r\nMale,75.2059736142212,228.761780615196\r\nMale,67.8931963386043,162.006651848287\r\nMale,68.1440327982008,192.343976579187\r\nMale,69.0896314289256,184.435174408406\r\nMale,72.8008435165003,206.828189420354\r\nMale,67.4212422817167,175.213922399227\r\nMale,68.4964153568827,154.342638925955\r\nMale,68.6181105502058,187.506843155807\r\nMale,74.0338076216678,212.910225325521\r\nMale,71.5282160355709,195.032243233835\r\nMale,69.1801610995692,205.183621341371\r\nMale,69.577202365402,204.164125484101\r\nMale,70.4009288884762,192.903515074649\r\nMale,69.0761711675356,197.488242598925\r\nMale,67.1935232827228,183.810973232751\r\nMale,65.8073156549306,163.851824878622\r\nMale,64.3041878915595,163.108017147583\r\nMale,67.9743362271967,172.135597406825\r\nMale,72.1894259592134,194.045404898059\r\nMale,65.2703455240394,168.617746204292\r\nMale,66.0901773762725,161.193432596622\r\nMale,67.5103215157138,164.660277264007\r\nMale,70.1047862551571,188.922303151274\r\nMale,68.2518364408672,187.060552163801\r\nMale,72.1727091157973,209.070863390252\r\nMale,69.1798576188774,192.014335412005\r\nMale,72.870360147235,211.342496819640\r\nMale,64.7825829779871,165.611626182250\r\nMale,70.1835498874837,201.071918099568\r\nMale,68.4914502529394,173.423960346601\r\nMale,67.3308308810162,181.407679285937\r\nMale,66.9909440825232,169.737707400252\r\nMale,66.4995499002499,163.309528309674\r\nMale,68.3530566463988,189.710209942456\r\nMale,70.7744590703974,192.124847346168\r\nMale,71.2159236694709,198.1984641076\r\nMale,70.0133653490674,209.526499837126\r\nMale,71.4031822207589,198.759792659859\r\nMale,69.5520050948319,198.079523654438\r\nMale,73.8185345577699,195.290612189727\r\nMale,66.99688275225,164.943302997003\r\nMale,71.4184658930907,179.863902339297\r\nMale,65.2793002090043,155.250420694049\r\nMale,68.2741914742284,184.519391248574\r\nMale,72.7653699463424,220.678041465283\r\nMale,68.0993798003468,183.31265530722\r\nMale,68.8967060721692,196.451312291183\r\nMale,69.2895099633052,184.595608300273\r\nMale,70.5232245234565,207.532838518544\r\nMale,69.6637252265179,177.200928752348\r\nMale,67.5952688079157,163.108002209381\r\nMale,72.5081203801037,216.218230112735\r\nMale,71.2529856038086,204.655493822323\r\nMale,71.8091868893668,200.920571219495\r\nMale,72.2451654792519,220.901769881142\r\nMale,66.5126276609347,196.449860340782\r\nMale,66.0290340048182,168.640810039015\r\nMale,67.577153942735,181.432713008126\r\nMale,68.2465686016242,198.658673326418\r\nMale,73.8261270026308,237.916735863185\r\nMale,69.8024643604904,173.041255909233\r\nMale,65.9595777848988,160.683916639879\r\nMale,71.0790175757451,188.602919070666\r\nMale,66.5961965372077,208.345694035109\r\nMale,68.9515350928246,193.435118452271\r\nMale,68.2444617923064,174.109693790620\r\nMale,72.3168251228452,197.368589249335\r\nMale,71.8154204495308,201.620666747742\r\nMale,65.2370495188386,181.011973240364\r\nMale,70.6405300907292,182.122485978660\r\nMale,64.731925597255,177.549263423371\r\nMale,67.1035511824075,164.974580682475\r\nMale,65.1174848880457,165.717112190107\r\nMale,71.7012340230177,193.094163543063\r\nMale,66.8328782059274,180.683886970857\r\nMale,66.4712752615182,172.773722928412\r\nMale,69.4115262206039,177.470616229738\r\nMale,70.0521774745245,200.818737313254\r\nMale,66.7436046519631,167.739775344302\r\nMale,66.2743291154144,154.395624779233\r\nMale,68.328447992915,177.984728603887\r\nMale,70.0758881952341,183.938856956780\r\nMale,68.7329881487344,179.204782068600\r\nMale,67.556051261876,158.567987385418\r\nMale,66.2536325347937,166.503531642942\r\nMale,69.1822026805756,171.983677611956\r\nMale,67.6091049416397,174.36418237859\r\nMale,69.2927380218867,187.745351863374\r\nMale,68.1906840077038,201.487962380610\r\nMale,71.6070857988906,204.927012136803\r\nMale,69.1968575103315,178.685546470181\r\nMale,67.2619609790619,164.014427741951\r\nMale,73.6851933999998,223.270004412371\r\nMale,69.5372150072948,202.958306269835\r\nMale,68.3115598414683,189.391785609949\r\nMale,67.7389634664393,178.170555578466\r\nMale,71.7057626011001,223.299335239803\r\nMale,63.6322646037867,167.028706658323\r\nMale,68.7211984556865,180.468682011870\r\nMale,66.9493416501869,164.439145622362\r\nMale,62.7069897353164,149.969618421042\r\nMale,72.2584089235993,192.910266551722\r\nMale,70.9086530626676,201.883998700574\r\nMale,67.609843601682,179.868025984495\r\nMale,70.8015589556942,196.467724673936\r\nMale,69.3047690450735,187.551649491386\r\nMale,66.2428983411553,171.69315968571\r\nMale,67.4921929772739,191.699604784328\r\nMale,65.8062482913584,165.850647784905\r\nMale,71.4437056615428,185.662741323862\r\nMale,68.4644058223141,178.281800729884\r\nMale,63.98792460498,150.979051250134\r\nMale,71.0018976858456,209.929323430504\r\nMale,68.1397241925525,174.157804341493\r\nMale,68.395400248121,179.878977102334\r\nMale,68.0962197450165,167.747141247633\r\nMale,68.1405903559209,183.044660372103\r\nMale,68.8600903087433,169.556820782151\r\nMale,66.1488525422307,173.431672660432\r\nMale,66.2060320529589,180.889554609418\r\nMale,67.4321202146878,183.508932854723\r\nMale,69.471106031247,205.977910165675\r\nMale,70.5158596943462,183.759845192649\r\nMale,71.3383760399558,201.954495466668\r\nMale,71.0019447673538,216.120094736912\r\nMale,66.202347706273,159.390323744187\r\nMale,72.5433070453887,210.336424661861\r\nMale,67.4793517580411,178.618350159953\r\nMale,65.3504105558103,146.739797635802\r\nMale,70.8440624208882,195.937014974314\r\nMale,69.9384752593112,170.175853813004\r\nMale,64.7398154829922,169.654054121188\r\nMale,69.3084028803936,198.378693643572\r\nMale,68.8384628598724,179.907716915983\r\nMale,61.9373232676829,147.263686501559\r\nMale,68.5933355351181,176.984251121287\r\nMale,65.2185755780772,185.467788373205\r\nMale,64.3336481069845,177.49380233889\r\nMale,68.7489067017398,169.827477419625\r\nMale,72.4896554004081,198.581698249799\r\nMale,67.2339309182551,203.350339274846\r\nMale,67.263604843261,193.217672687431\r\nMale,65.1185042831735,178.134945178843\r\nMale,66.2628200381632,162.779583404690\r\nMale,67.7016796596273,159.286510598869\r\nMale,65.530695966695,172.114311951227\r\nMale,69.8689698092041,201.837042594883\r\nMale,68.481875364733,170.352329550626\r\nMale,72.2139633457195,205.389760708631\r\nMale,68.1795326940723,169.787768075943\r\nMale,71.9812065428705,200.437310528735\r\nMale,66.0651367327304,178.588954037204\r\nMale,66.6561641698185,168.014029738329\r\nMale,67.5994241952902,177.766425839946\r\nMale,68.245944093831,193.277623999542\r\nMale,64.808621440717,162.379540639612\r\nMale,67.4922182698406,183.383824391458\r\nMale,68.1807307068654,181.056095285359\r\nMale,69.553384902902,210.871798957101\r\nMale,66.4022496683603,165.568499073011\r\nMale,66.5921571146877,196.148449846229\r\nMale,71.9358865828482,202.046425151919\r\nMale,68.2870417278818,170.413602496365\r\nMale,69.9554511951638,201.948085296608\r\nMale,71.8511291454027,193.386984552842\r\nMale,65.7554986406737,179.855689615225\r\nMale,67.0318520789828,156.489934998191\r\nMale,76.7098348578592,235.035418820022\r\nMale,72.5711213712958,230.560534959742\r\nMale,69.7288048973671,203.895654986365\r\nMale,72.799224004586,218.216396639014\r\nMale,72.5393540719418,222.667177921523\r\nMale,72.2947433844169,208.474865890573\r\nMale,67.2533248158638,180.779780013772\r\nMale,75.9444603760016,231.924748509110\r\nMale,66.3162319187446,170.593858104457\r\nMale,71.1560534900436,188.271456288347\r\nMale,71.1922022869477,196.061529163376\r\nMale,72.1975120071642,214.603584170431\r\nMale,75.1408214339315,224.124271329560\r\nMale,64.4115293597211,158.579397323387\r\nMale,64.7344243580774,166.501114745286\r\nMale,63.4145871379546,160.140615622405\r\nMale,67.8486652335686,176.172634254583\r\nMale,65.9317848288,174.485294666451\r\nMale,70.9665504363426,193.906498798923\r\nMale,67.5807472772935,186.991606706801\r\nMale,68.589270437901,173.595796099507\r\nMale,70.3247534441504,193.346560303991\r\nMale,72.3944804051075,208.436509038226\r\nMale,70.8208567145256,206.032977800797\r\nMale,65.9033012610258,172.57523095707\r\nMale,74.7953750218274,232.635402847360\r\nMale,67.6809190342573,177.24014549544\r\nMale,67.1559627687305,175.646690214202\r\nMale,71.7748412248401,212.626102288605\r\nMale,64.6652319449664,166.969204009677\r\nMale,68.1227683623759,196.414415275124\r\nMale,66.786927239528,165.431242225646\r\nMale,66.805849836748,176.565818557689\r\nMale,67.8860137980274,174.652034715810\r\nMale,69.1735769192432,195.237529301091\r\nMale,70.2249233263794,205.684438396274\r\nMale,64.8557991775539,158.341442360480\r\nMale,67.8210932715426,169.081008273884\r\nMale,63.4402474670865,135.655875865835\r\nMale,71.8484348479039,218.157469450706\r\nMale,66.7280736470863,155.899541329016\r\nMale,71.9683056520603,201.528177430467\r\nMale,76.0213474760963,235.926060648678\r\nMale,71.4761012826014,195.392617577504\r\nMale,67.3698086448686,176.636163567362\r\nMale,70.5552437595499,198.460248600108\r\nMale,69.8671012814472,185.716910023673\r\nMale,67.9475700421625,177.347779818472\r\nMale,74.104558863713,215.759703523821\r\nMale,69.167836299535,187.022420301570\r\nMale,66.557228572704,171.587884316854\r\nMale,66.7016049901078,172.839809078093\r\nMale,67.2460649543824,168.280286893893\r\nMale,69.0513854849974,163.820488927750\r\nMale,70.6727471767308,190.023434180521\r\nMale,65.4989951214088,156.869951668729\r\nMale,65.1872208535622,172.606482559614\r\nMale,67.5681430060826,169.063982994918\r\nMale,73.8153856882339,231.374508117238\r\nMale,71.606564208448,207.250476751691\r\nMale,67.724749235945,172.152772178008\r\nMale,68.231131952185,199.827758022834\r\nMale,65.9294217100738,168.090412215803\r\nMale,71.5484957096636,197.819614833288\r\nMale,69.1643811220365,196.892315040706\r\nMale,68.5976593239588,180.221780102342\r\nMale,71.0575108857852,189.134012435934\r\nMale,63.6440595814991,158.422717319974\r\nMale,71.1824553956369,208.922682655891\r\nMale,66.1286731698491,187.141119453372\r\nMale,65.0573731150978,157.582431535246\r\nMale,68.0913743588464,181.644444983884\r\nMale,70.993143899047,204.746678174754\r\nMale,74.2211748776249,231.130189759308\r\nMale,69.3271181795885,186.258429614423\r\nMale,64.9313421940842,181.093869638880\r\nMale,68.3468423145436,198.920979667801\r\nMale,70.9291250844694,203.370463215939\r\nMale,61.4778092015939,161.028752141872\r\nMale,68.4908127185185,189.806681842181\r\nMale,72.0498898708186,200.202828506602\r\nMale,72.5216670257767,221.862650308484\r\nMale,71.233911393331,214.060148220865\r\nMale,72.2591151862599,201.701421617410\r\nMale,67.5650399045651,187.187093632233\r\nMale,72.26760699498,196.527466895855\r\nMale,62.6002479975529,151.720703729313\r\nMale,66.2364372917754,167.297530251137\r\nMale,69.6504374123688,198.843695964623\r\nMale,69.2859214061721,178.789547981921\r\nMale,70.7252787373505,193.539252115985\r\nMale,68.8286149599904,197.737905022318\r\nMale,66.0144282335004,184.461811520982\r\nMale,66.4148820603895,155.194771686925\r\nMale,66.6156243917126,160.991989871194\r\nMale,68.0348217821036,189.084461735075\r\nMale,70.5023980440946,172.985777146208\r\nMale,69.1577294930868,195.895256857188\r\nMale,70.7950226136223,215.746455305230\r\nMale,65.1943771233415,166.707373059357\r\nMale,74.7857143190925,239.464342902696\r\nMale,71.0669062761598,184.279245833050\r\nMale,69.334197785954,199.983890906512\r\nMale,69.8992039506227,191.412231132701\r\nMale,64.4251937917821,169.109401417791\r\nMale,67.85213069861,194.744522494038\r\nMale,67.549069488044,183.266533117893\r\nMale,74.7674468449337,210.369908709756\r\nMale,71.4189459863648,198.042483889936\r\nMale,67.1203443862066,172.664090375104\r\nMale,69.8595879120267,197.070856157865\r\nMale,68.4308133914105,190.505810039573\r\nMale,67.9334826070233,184.555483105293\r\nMale,68.4953431552723,179.929816647941\r\nMale,65.2441434106539,159.503219765390\r\nMale,70.18535204699,197.884507071155\r\nMale,71.1041331645307,217.269605198307\r\nMale,68.4475785430627,187.907425986628\r\nMale,65.4205768240508,176.861684237851\r\nMale,67.7007881137183,185.148202101777\r\nMale,74.2230630621199,223.308040304474\r\nMale,71.1672458708534,206.942981776074\r\nMale,67.2307718899502,171.016940600979\r\nMale,67.880559193661,175.222847965396\r\nMale,67.3763754684836,173.310395551927\r\nMale,68.7612469290256,181.125973501963\r\nMale,71.7052725009646,202.609008338003\r\nMale,69.3809947926619,199.850920048803\r\nMale,73.7165276342286,223.514722344292\r\nMale,69.4533762078207,219.261706666844\r\nMale,70.7862898094215,211.216080923481\r\nMale,71.7684637369012,200.798982967421\r\nMale,69.3434539586165,208.809775337563\r\nMale,65.2860255086334,161.420081658509\r\nMale,70.9218444138077,207.835944561795\r\nMale,68.5966626863791,180.831237755497\r\nMale,68.6037964328568,176.815476209732\r\nMale,69.4787441197736,194.603768502719\r\nMale,65.9308962149966,163.008431653289\r\nMale,68.5233452979566,173.270657154824\r\nMale,73.9291241262215,215.620035427178\r\nMale,71.1979378222303,210.134529042031\r\nMale,66.5565868729681,185.042324084993\r\nMale,71.7422762291745,187.965355359453\r\nMale,69.7448293316538,188.181124848229\r\nMale,66.7506541256505,179.542017143198\r\nMale,69.6924222571513,211.718428961730\r\nMale,70.4035168308414,197.692142083456\r\nMale,69.0197361098685,186.287991990979\r\nMale,64.732287155256,166.106072437390\r\nMale,70.9980744408969,188.811769976897\r\nMale,64.4598142530512,161.378773212037\r\nMale,69.749522583002,193.476258831235\r\nMale,71.5268488121848,189.282246099829\r\nMale,68.327915863972,207.784924645001\r\nMale,70.7647201641119,199.323094259304\r\nMale,71.4190496341516,209.858256604748\r\nMale,69.3904740948909,180.175472763871\r\nMale,72.001732217799,196.214414481383\r\nMale,69.1914749733353,189.438840351539\r\nMale,66.1663632831791,165.514607433147\r\nMale,67.272142995153,182.39433469242\r\nMale,70.9158354035361,189.557637460086\r\nMale,69.1198877896665,189.625914076302\r\nMale,67.409025871346,170.191325429211\r\nMale,72.938649040208,216.097454719831\r\nMale,70.4909286959958,177.067774350773\r\nMale,69.0082594618674,196.051188755039\r\nMale,66.7621099176273,167.700496231312\r\nMale,69.1206637294553,179.607870051102\r\nMale,73.1262671878997,220.661405093753\r\nMale,67.4868238954174,164.295241252612\r\nMale,64.95507833495,156.544786349540\r\nMale,67.7824890749697,183.681029038066\r\nMale,67.662398796047,170.305493490476\r\nMale,66.4763970064683,168.627263912841\r\nMale,72.9870702010434,209.637974489395\r\nMale,69.5632322771984,195.346026970440\r\nMale,71.0035601394697,194.322601360166\r\nMale,69.9156373621056,219.367916747189\r\nMale,71.697141788046,205.161748286445\r\nMale,67.6499408575301,178.882633665742\r\nMale,68.2955545645253,181.724931465833\r\nMale,68.687255673712,203.560333836071\r\nMale,68.9157716453463,165.155898683434\r\nMale,68.9608796727544,197.931429550253\r\nMale,67.2472352041876,173.284033013291\r\nMale,68.915863641061,183.947788899966\r\nMale,65.8385445036175,139.534046940100\r\nMale,64.6710755478367,160.188531344114\r\nMale,66.2958977236134,163.604002191910\r\nMale,67.0975857472015,193.955107443761\r\nMale,66.998289732799,189.893342494401\r\nMale,70.9619709026438,184.223932043739\r\nMale,68.4208722048485,190.795542169576\r\nMale,67.6525275866462,188.200679380904\r\nMale,75.6201931582543,226.207779869446\r\nMale,70.549242022249,197.879373104868\r\nMale,68.8908389093416,190.51348690364\r\nMale,68.2845319195117,176.246583436270\r\nMale,64.9950782592052,177.727094498411\r\nMale,65.5757715426728,173.691592194197\r\nMale,69.3060882402712,210.463687540605\r\nMale,65.7047154221532,170.100563318173\r\nMale,67.8039910102957,173.459891805983\r\nMale,69.2161473119131,184.936690322645\r\nMale,68.015006008896,194.286945947274\r\nMale,61.9269489433641,149.149684837724\r\nMale,67.2663627155588,192.4707695606\r\nMale,67.6768218539142,179.750807982436\r\nMale,69.9709036159667,202.863293032098\r\nMale,65.3134615369232,163.357331518913\r\nMale,71.9060054405707,217.027714643657\r\nMale,66.2339040421843,183.16123245569\r\nMale,65.814942824229,166.583610507509\r\nMale,72.8449478550183,205.250889151117\r\nMale,70.9494434526129,189.703088823966\r\nMale,71.3438076277468,218.586336397370\r\nMale,71.0556641579506,203.139433025567\r\nMale,61.9255472947778,139.905070315411\r\nMale,68.7624575579021,196.293805874861\r\nMale,67.5839414255894,179.937011167166\r\nMale,67.3616946688862,164.145922397398\r\nMale,65.8791565562673,168.174864370716\r\nMale,68.6947621511413,189.742541903603\r\nMale,69.5348615536043,195.170391498940\r\nMale,66.6346908282865,190.467958779164\r\nMale,69.8099015736912,204.426598301005\r\nMale,68.6798736853237,196.151622823601\r\nMale,71.615178750348,209.670773879197\r\nMale,69.6897953335489,190.933400489868\r\nMale,70.9010863653248,197.944832362141\r\nMale,68.005813992332,186.78033784958\r\nMale,70.6157439783607,188.663832117765\r\nMale,71.5711941575576,176.376642766115\r\nMale,73.0128632629827,209.329483369428\r\nMale,60.748117867457,136.167865724177\r\nMale,69.082119625473,190.935182500985\r\nMale,69.3387376279613,191.445654280964\r\nMale,67.7571377115653,184.938229910773\r\nMale,76.0270818630512,232.313470969478\r\nMale,72.2276161601432,201.778853950381\r\nMale,68.9210413450252,188.328807061518\r\nMale,65.334927680754,174.655697250193\r\nMale,65.932403451767,183.943338755166\r\nMale,70.4666893102283,187.517442017500\r\nMale,73.181043621139,213.847452872237\r\nMale,68.550879686478,175.219518795655\r\nMale,68.5294082502857,169.544805445436\r\nMale,63.5964554204545,144.591922421247\r\nMale,67.1442412277953,175.679190176701\r\nMale,70.8163706158515,197.198401561075\r\nMale,73.530284807779,222.925916699257\r\nMale,66.1410689194018,165.404545337709\r\nMale,67.9068497483934,170.417231213329\r\nMale,71.4333758216347,216.633999687682\r\nMale,67.1126797980262,173.707504236685\r\nMale,73.2839179655908,217.896039742328\r\nMale,63.6725831540933,161.013145838894\r\nMale,69.2253203013539,193.756325798869\r\nMale,69.6701240248717,177.119160725399\r\nMale,70.4854481656936,204.827449737938\r\nMale,69.0046778666841,176.731892478922\r\nMale,68.4578940081104,192.761885655036\r\nMale,66.024733782518,166.961020473440\r\nMale,69.3181691252784,186.737995548307\r\nMale,69.0777405646964,188.506178710684\r\nMale,73.5622703667904,208.361491812853\r\nMale,66.0876888866475,161.495814307993\r\nMale,73.5259843332352,214.966459199799\r\nMale,69.6790602156639,205.133435498665\r\nMale,66.6767811169297,183.197306840047\r\nMale,72.9616654677117,208.895044285857\r\nMale,68.246872144459,207.925576545187\r\nMale,71.9566258887157,210.663827812062\r\nMale,71.0586333491432,204.272837745409\r\nMale,66.9769499482511,195.198730107264\r\nMale,68.478002075726,190.686022530134\r\nMale,71.2844413912849,199.635326578537\r\nMale,64.980456290984,166.821547345859\r\nMale,66.7618838734058,178.797508975099\r\nMale,68.7661617238793,185.772157505947\r\nMale,68.9925435671764,193.754990936111\r\nMale,71.295194595564,228.800516094148\r\nMale,69.0494784004474,192.349701712414\r\nMale,66.5414820162944,175.983491137569\r\nMale,68.5155234451208,176.141239163871\r\nMale,67.459715

In [11]:
df = pd.read_csv('weight-height.csv')

In [6]:
print(df.to_string())

      Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
5       Male  67.253016  152.212156
6       Male  68.785081  183.927889
7       Male  68.348516  167.971110
8       Male  67.018950  175.929440
9       Male  63.456494  156.399676
10      Male  71.195382  186.604926
11      Male  71.640805  213.741169
12      Male  64.766329  167.127461
13      Male  69.283070  189.446181
14      Male  69.243732  186.434168
15      Male  67.645620  172.186930
16      Male  72.418317  196.028506
17      Male  63.974326  172.883470
18      Male  69.640060  185.983958
19      Male  67.936005  182.426648
20      Male  67.915050  174.115929
21      Male  69.439440  197.731422
22      Male  66.149132  149.173566
23      Male  75.205974  228.761781
24      Male  67.893196  162.006652
25      Male  68.144033  192.343977
26      Male  69.089631  184.435174
27      Male  72.800844  206.828189
28      Male  67.421242  175.213922
29      Male  68.496415  154.342639
30      Male  68.618111  187.506843
31      Male  74.033808  212.910225
32      Male  71.528216  195.032243
33      Male  69.180161  205.183621
34      Male  69.577202  204.164125
35      Male  70.400929  192.903515
36      Male  69.076171  197.488243
37      Male  67.193523  183.810973
38      Male  65.807316  163.851825
39      Male  64.304188  163.108017
40      Male  67.974336  172.135597
41      Male  72.189426  194.045405
42      Male  65.270346  168.617746
43      Male  66.090177  161.193433
44      Male  67.510322  164.660277
45      Male  70.104786  188.922303
46      Male  68.251836  187.060552
47      Male  72.172709  209.070863
48      Male  69.179858  192.014335
49      Male  72.870360  211.342497
50      Male  64.782583  165.611626
51      Male  70.183550  201.071918
52      Male  68.491450  173.423960
53      Male  67.330831  181.407679
54      Male  66.990944  169.737707
55      Male  66.499550  163.309528
56      Male  68.353057  189.710210
57      Male  70.774459  192.124847
58      Male  71.215924  198.198464
59      Male  70.013365  209.526500
60      Male  71.403182  198.759793
61      Male  69.552005  198.079524
62      Male  73.818535  195.290612
63      Male  66.996883  164.943303
64      Male  71.418466  179.863902
65      Male  65.279300  155.250421
66      Male  68.274191  184.519391
67      Male  72.765370  220.678041
68      Male  68.099380  183.312655
69      Male  68.896706  196.451312
70      Male  69.289510  184.595608
71      Male  70.523225  207.532839
72      Male  69.663725  177.200929
73      Male  67.595269  163.108002
74      Male  72.508120  216.218230
75      Male  71.252986  204.655494
76      Male  71.809187  200.920571
77      Male  72.245165  220.901770
78      Male  66.512628  196.449860
79      Male  66.029034  168.640810
80      Male  67.577154  181.432713
81      Male  68.246569  198.658673
82      Male  73.826127  237.916736
83      Male  69.802464  173.041256
84      Male  65.959578  160.683917
85      Male  71.079018  188.602919
86      Male  66.596197  208.345694
87      Male  68.951535  193.435118
88      Male  68.244462  174.109694
89      Male  72.316825  197.368589
90      Male  71.815420  201.620667
91      Male  65.237050  181.011973
92      Male  70.640530  182.122486
93      Male  64.731926  177.549263
94      Male  67.103551  164.974581
95      Male  65.117485  165.717112
96      Male  71.701234  193.094164
97      Male  66.832878  180.683887
98      Male  66.471275  172.773723
99      Male  69.411526  177.470616
100     Male  70.052177  200.818737
101     Male  66.743605  167.739775
102     Male  66.274329  154.395625
103     Male  68.328448  177.984729
104     Male  70.075888  183.938857
105     Male  68.732988  179.204782
106     Male  67.556051  158.567987
107     Male  66.253633  166.503532
108     Male  69.182203  171.983678
109     Male  67.609105  174.364182
110     Male  69.292738  187.745352
111     Male  68.190684  201.487962
112     Male  71.607086  204.927012
113     Male  69.196858  178.685546
114     Male  67.261961  164.014428
115     Male  73.685193  223.270004
116     Male  69.537215  202.958306
117     Male  68.311560  189.391786
118     Male  67.738963  178.170556
119     Male  71.705763  223.299335
120     Male  63.632265  167.028707
121     Male  68.721198  180.468682
122     Male  66.949342  164.439146
123     Male  62.706990  149.969618
124     Male  72.258409  192.910267
125     Male  70.908653  201.883999
126     Male  67.609844  179.868026
127     Male  70.801559  196.467725
128     Male  69.304769  187.551649
129     Male  66.242898  171.693160
130     Male  67.492193  191.699605
131     Male  65.806248  165.850648
132     Male  71.443706  185.662741
133     Male  68.464406  178.281801
134     Male  63.987925  150.979051
135     Male  71.001898  209.929323
136     Male  68.139724  174.157804
137     Male  68.395400  179.878977
138     Male  68.096220  167.747141
139     Male  68.140590  183.044660
140     Male  68.860090  169.556821
141     Male  66.148853  173.431673
142     Male  66.206032  180.889555
143     Male  67.432120  183.508933
144     Male  69.471106  205.977910
145     Male  70.515860  183.759845
146     Male  71.338376  201.954495
147     Male  71.001945  216.120095
148     Male  66.202348  159.390324
149     Male  72.543307  210.336425
150     Male  67.479352  178.618350
151     Male  65.350411  146.739798
152     Male  70.844062  195.937015
153     Male  69.938475  170.175854
154     Male  64.739815  169.654054
155     Male  69.308403  198.378694
156     Male  68.838463  179.907717
157     Male  61.937323  147.263687
158     Male  68.593336  176.984251
159     Male  65.218576  185.467788
160     Male  64.333648  177.493802
161     Male  68.748907  169.827477
162     Male  72.489655  198.581698
163     Male  67.233931  203.350339
164     Male  67.263605  193.217673
165     Male  65.118504  178.134945
166     Male  66.262820  162.779583
167     Male  67.701680  159.286511
168     Male  65.530696  172.114312
169     Male  69.868970  201.837043
170     Male  68.481875  170.352330
171     Male  72.213963  205.389761
172     Male  68.179533  169.787768
173     Male  71.981207  200.437311
174     Male  66.065137  178.588954
175     Male  66.656164  168.014030
176     Male  67.599424  177.766426
177     Male  68.245944  193.277624
178     Male  64.808621  162.379541
179     Male  67.492218  183.383824
180     Male  68.180731  181.056095
181     Male  69.553385  210.871799
182     Male  66.402250  165.568499
183     Male  66.592157  196.148450
184     Male  71.935887  202.046425
185     Male  68.287042  170.413602
186     Male  69.955451  201.948085
187     Male  71.851129  193.386985
188     Male  65.755499  179.855690
189     Male  67.031852  156.489935
190     Male  76.709835  235.035419
191     Male  72.571121  230.560535
192     Male  69.728805  203.895655
193     Male  72.799224  218.216397
194     Male  72.539354  222.667178
195     Male  72.294743  208.474866
196     Male  67.253325  180.779780
197     Male  75.944460  231.924749
198     Male  66.316232  170.593858
199     Male  71.156053  188.271456
200     Male  71.192202  196.061529
201     Male  72.197512  214.603584
202     Male  75.140821  224.124271
203     Male  64.411529  158.579397
204     Male  64.734424  166.501115
205     Male  63.414587  160.140616
206     Male  67.848665  176.172634
207     Male  65.931785  174.485295
208     Male  70.966550  193.906499
209     Male  67.580747  186.991607
210     Male  68.589270  173.595796
211     Male  70.324753  193.346560
212     Male  72.394480  208.436509
213     Male  70.820857  206.032978
214     Male  65.903301  172.575231
215     Male  74.795375  232.635403
216     Male  67.680919  177.240145
217     Male  67.155963  175.646690
218     Male  71.774841  212.626102
219     Male  64.665232  166.969204
220     Male  68.122768  196.414415
221     Male  66.786927  165.431242
222     Male  66.805850  176.565819
223     Male  67.886014  174.652035
224     Male  69.173577  195.237529
225     Male  70.224923  205.684438
226     Male  64.855799  158.341442
227     Male  67.821093  169.081008
228     Male  63.440247  135.655876
229     Male  71.848435  218.157469
230     Male  66.728074  155.899541
231     Male  71.968306  201.528177
232     Male  76.021347  235.926061
233     Male  71.476101  195.392618
234     Male  67.369809  176.636164
235     Male  70.555244  198.460249
236     Male  69.867101  185.716910
237     Male  67.947570  177.347780
238     Male  74.104559  215.759704
239     Male  69.167836  187.022420
240     Male  66.557229  171.587884
241     Male  66.701605  172.839809
242     Male  67.246065  168.280287
243     Male  69.051385  163.820489
244     Male  70.672747  190.023434
245     Male  65.498995  156.869952
246     Male  65.187221  172.606483
247     Male  67.568143  169.063983
248     Male  73.815386  231.374508
249     Male  71.606564  207.250477
250     Male  67.724749  172.152772
251     Male  68.231132  199.827758
252     Male  65.929422  168.090412
253     Male  71.548496  197.819615
254     Male  69.164381  196.892315
255     Male  68.597659  180.221780
256     Male  71.057511  189.134012
257     Male  63.644060  158.422717
258     Male  71.182455  208.922683
259     Male  66.128673  187.141119
260     Male  65.057373  157.582432
261     Male  68.091374  181.644445
262     Male  70.993144  204.746678
263     Male  74.221175  231.130190
264     Male  69.327118  186.258430
265     Male  64.931342  181.093870
266     Male  68.346842  198.920980
267     Male  70.929125  203.370463
268     Male  61.477809  161.028752
269     Male  68.490813  189.806682
270     Male  72.049890  200.202829
271     Male  72.521667  221.862650
272     Male  71.233911  214.060148
273     Male  72.259115  201.701422
274     Male  67.565040  187.187094
275     Male  72.267607  196.527467
276     Male  62.600248  151.720704
277     Male  66.236437  167.297530
278     Male  69.650437  198.843696
279     Male  69.285921  178.789548
280     Male  70.725279  193.539252
281     Male  68.828615  197.737905
282     Male  66.014428  184.461812
283     Male  66.414882  155.194772
284     Male  66.615624  160.991990
285     Male  68.034822  189.084462
286     Male  70.502398  172.985777
287     Male  69.157729  195.895257
288     Male  70.795023  215.746455
289     Male  65.194377  166.707373
290     Male  74.785714  239.464343
291     Male  71.066906  184.279246
292     Male  69.334198  199.983891
293     Male  69.899204  191.412231
294     Male  64.425194  169.109401
295     Male  67.852131  194.744522
296     Male  67.549069  183.266533
297     Male  74.767447  210.369909
298     Male  71.418946  198.042484
299     Male  67.120344  172.664090
300     Male  69.859588  197.070856
301     Male  68.430813  190.505810
302     Male  67.933483  184.555483
303     Male  68.495343  179.929817
304     Male  65.244143  159.503220
305     Male  70.185352  197.884507
306     Male  71.104133  217.269605
307     Male  68.447579  187.907426
308     Male  65.420577  176.861684
309     Male  67.700788  185.148202
310     Male  74.223063  223.308040
311     Male  71.167246  206.942982
312     Male  67.230772  171.016941
313     Male  67.880559  175.222848
314     Male  67.376375  173.310396
315     Male  68.761247  181.125974
316     Male  71.705273  202.609008
317     Male  69.380995  199.850920
318     Male  73.716528  223.514722
319     Male  69.453376  219.261707
320     Male  70.786290  211.216081
321     Male  71.768464  200.798983
322     Male  69.343454  208.809775
323     Male  65.286026  161.420082
324     Male  70.921844  207.835945
325     Male  68.596663  180.831238
326     Male  68.603796  176.815476
327     Male  69.478744  194.603769
328     Male  65.930896  163.008432
329     Male  68.523345  173.270657
330     Male  73.929124  215.620035
331     Male  71.197938  210.134529
332     Male  66.556587  185.042324
333     Male  71.742276  187.965355
334     Male  69.744829  188.181125
335     Male  66.750654  179.542017
336     Male  69.692422  211.718429
337     Male  70.403517  197.692142
338     Male  69.019736  186.287992
339     Male  64.732287  166.106072
340     Male  70.998074  188.811770
341     Male  64.459814  161.378773
342     Male  69.749523  193.476259
343     Male  71.526849  189.282246
344     Male  68.327916  207.784925
345     Male  70.764720  199.323094
346     Male  71.419050  209.858257
347     Male  69.390474  180.175473
348     Male  72.001732  196.214414
349     Male  69.191475  189.438840
350     Male  66.166363  165.514607
351     Male  67.272143  182.394335
352     Male  70.915835  189.557637
353     Male  69.119888  189.625914
354     Male  67.409026  170.191325
355     Male  72.938649  216.097455
356     Male  70.490929  177.067774
357     Male  69.008259  196.051189
358     Male  66.762110  167.700496
359     Male  69.120664  179.607870
360     Male  73.126267  220.661405
361     Male  67.486824  164.295241
362     Male  64.955078  156.544786
363     Male  67.782489  183.681029
364     Male  67.662399  170.305493
365     Male  66.476397  168.627264
366     Male  72.987070  209.637974
367     Male  69.563232  195.346027
368     Male  71.003560  194.322601
369     Male  69.915637  219.367917
370     Male  71.697142  205.161748
371     Male  67.649941  178.882634
372     Male  68.295555  181.724931
373     Male  68.687256  203.560334
374     Male  68.915772  165.155899
375     Male  68.960880  197.931430
376     Male  67.247235  173.284033
377     Male  68.915864  183.947789
378     Male  65.838545  139.534047
379     Male  64.671076  160.188531
380     Male  66.295898  163.604002
381     Male  67.097586  193.955107
382     Male  66.998290  189.893342
383     Male  70.961971  184.223932
384     Male  68.420872  190.795542
385     Male  67.652528  188.200679
386     Male  75.620193  226.207780
387     Male  70.549242  197.879373
388     Male  68.890839  190.513487
389     Male  68.284532  176.246583
390     Male  64.995078  177.727094
391     Male  65.575772  173.691592
392     Male  69.306088  210.463688
393     Male  65.704715  170.100563
394     Male  67.803991  173.459892
395     Male  69.216147  184.936690
396     Male  68.015006  194.286946
397     Male  61.926949  149.149685
398     Male  67.266363  192.470770
399     Male  67.676822  179.750808
400     Male  69.970904  202.863293
401     Male  65.313462  163.357332
402     Male  71.906005  217.027715
403     Male  66.233904  183.161232
404     Male  65.814943  166.583611
405     Male  72.844948  205.250889
406     Male  70.949443  189.703089
407     Male  71.343808  218.586336
408     Male  71.055664  203.139433
409     Male  61.925547  139.905070
410     Male  68.762458  196.293806
411     Male  67.583941  179.937011
412     Male  67.361695  164.145922
413     Male  65.879157  168.174864
414     Male  68.694762  189.742542
415     Male  69.534862  195.170391
416     Male  66.634691  190.467959
417     Male  69.809902  204.426598
418     Male  68.679874  196.151623
419     Male  71.615179  209.670774
420     Male  69.689795  190.933400
421     Male  70.901086  197.944832
422     Male  68.005814  186.780338
423     Male  70.615744  188.663832
424     Male  71.571194  176.376643
425     Male  73.012863  209.329483
426     Male  60.748118  136.167866
427     Male  69.082120  190.935183
428     Male  69.338738  191.445654
429     Male  67.757138  184.938230
430     Male  76.027082  232.313471
431     Male  72.227616  201.778854
432     Male  68.921041  188.328807
433     Male  65.334928  174.655697
434     Male  65.932403  183.943339
435     Male  70.466689  187.517442
436     Male  73.181044  213.847453
437     Male  68.550880  175.219519
438     Male  68.529408  169.544805
439     Male  63.596455  144.591922
440     Male  67.144241  175.679190
441     Male  70.816371  197.198402
442     Male  73.530285  222.925917
443     Male  66.141069  165.404545
444     Male  67.906850  170.417231
445     Male  71.433376  216.634000
446     Male  67.112680  173.707504
447     Male  73.283918  217.896040
448     Male  63.672583  161.013146
449     Male  69.225320  193.756326
450     Male  69.670124  177.119161
451     Male  70.485448  204.827450
452     Male  69.004678  176.731892
453     Male  68.457894  192.761886
454     Male  66.024734  166.961020
455     Male  69.318169  186.737996
456     Male  69.077741  188.506179
457     Male  73.562270  208.361492
458     Male  66.087689  161.495814
459     Male  73.525984  214.966459
460     Male  69.679060  205.133435
461     Male  66.676781  183.197307
462     Male  72.961665  208.895044
463     Male  68.246872  207.925577
464     Male  71.956626  210.663828
465     Male  71.058633  204.272838
466     Male  66.976950  195.198730
467     Male  68.478002  190.686023
468     Male  71.284441  199.635327
469     Male  64.980456  166.821547
470     Male  66.761884  178.797509
471     Male  68.766162  185.772158
472     Male  68.992544  193.754991
473     Male  71.295195  228.800516
474     Male  69.049478  192.349702
475     Male  66.541482  175.983491
476     Male  68.515523  176.141239
477     Male  67.459715  177.482525
478     Male  71.357382  201.760777
479     Male  68.590406  176.843080
480     Male  69.736087  185.524260
481     Male  69.833857  188.041029
482     Male  72.410586  189.384438
483     Male  65.434597  166.096744
484     Male  66.267657  170.250179
485     Male  69.974301  212.804259
486     Male  71.209194  196.145506
487     Male  69.937400  202.279070
488     Male  71.386022  201.332007
489     Male  64.588782  158.454094
490     Male  68.792984  174.489486
491     Male  68.445747  183.783383
492     Male  69.201578  188.103506
493     Male  69.426017  176.193430
494     Male  69.606225  194.200712
495     Male  72.881707  194.199509
496     Male  62.178331  145.898842
497     Male  68.874707  191.833709
498     Male  71.080084  209.853554
499     Male  72.182534  201.261464
500     Male  72.062755  208.781853
501     Male  67.380058  182.673405
502     Male  67.934635  166.435069
503     Male  70.801930  193.393543
504     Male  65.549121  178.448180
505     Male  70.191224  205.941791
506     Male  71.778995  199.209842
507     Male  68.130288  192.029567
508     Male  68.359483  175.260864
509     Male  66.090357  170.006445
510     Male  71.580123  205.347596
511     Male  73.536668  196.043295
512     Male  71.115532  208.145257
513     Male  70.794303  202.890758
514     Male  71.729060  188.595024
515     Male  63.196530  162.429727
516     Male  68.101113  182.852399
517     Male  65.856100  157.317461
518     Male  68.346457  178.675992
519     Male  69.560229  187.217486
520     Male  68.728304  171.620967
521     Male  70.158278  200.534178
522     Male  68.923337  193.927360
523     Male  64.300174  155.489729
524     Male  70.455633  192.527905
525     Male  68.624063  159.862467
526     Male  69.664752  176.259274
527     Male  69.058885  171.708926
528     Male  67.226986  181.709619
529     Male  66.115800  171.386659
530     Male  68.617387  179.132025
531     Male  69.249013  187.469371
532     Male  69.641906  182.004522
533     Male  72.797028  214.474036
534     Male  75.043995  208.526427
535     Male  70.972684  190.221993
536     Male  74.388012  217.143790
537     Male  64.362164  156.073899
538     Male  71.327001  206.385191
539     Male  67.172024  178.152781
540     Male  74.401672  228.838396
541     Male  63.867921  174.473363
542     Male  68.885992  164.214903
543     Male  72.131990  212.157276
544     Male  68.403726  206.014940
545     Male  65.092656  167.433533
546     Male  69.229679  195.218640
547     Male  71.947788  209.175489
548     Male  67.462991  182.301286
549     Male  69.312909  190.185147
550     Male  63.731048  160.344904
551     Male  60.679817  129.301024
552     Male  70.663323  195.626319
553     Male  67.594031  186.751417

In [7]:
display(df.head())

  Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [8]:
display(df.tail())

      Gender     Height      Weight
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

In [9]:
display(df.head(15))

   Gender     Height      Weight
0    Male  73.847017  241.893563
1    Male  68.781904  162.310473
2    Male  74.110105  212.740856
3    Male  71.730978  220.042470
4    Male  69.881796  206.349801
5    Male  67.253016  152.212156
6    Male  68.785081  183.927889
7    Male  68.348516  167.971110
8    Male  67.018950  175.929440
9    Male  63.456494  156.399676
10   Male  71.195382  186.604926
11   Male  71.640805  213.741169
12   Male  64.766329  167.127461
13   Male  69.283070  189.446181
14   Male  69.243732  186.434168

In [10]:
display(df.tail(10))

      Gender     Height      Weight
9990  Female  63.179498  141.266100
9991  Female  62.636675  102.853563
9992  Female  62.077832  138.691680
9993  Female  60.030434   97.687432
9994  Female  59.098250  110.529686
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103



---

# Good Job !